# ----- STAGE 1: Build -----
FROM node:24.11.0 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --include=dev

COPY . .

RUN npm run build


# ----- STAGE 2: Production -----
FROM node:24.11.0

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "dist/index.js"]


